/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import jdk.nashorn.tools.Shell;
import lectura.ImageManager;

/**
 *
 * @author Roberto Cruz Leija
 */
public class ImagenJInternalFrameFiltros extends javax.swing.JInternalFrame {

    private Image imagenOriginal;
	private Image imagenRespaldo;
    /**
     * Creates new form ImagenJInternalFrame
     */
    public ImagenJInternalFrameFiltros(Image imagen) {
		
			initComponents();
			this.imagenOriginal = imagen;
			// mandar la imagen como icono al jlabel
			this.jLabelImagen.setIcon(new ImageIcon(imagen));
			this.imagenRespaldo = ImageManager.toImage(ImageManager.toBufferedImage(imagen));
			
			// redimensionar las dimensiones del jframe
			setSize(imagen.getWidth(null),imagen.getHeight(null));
			
			setVisible(true);
			this.setResizable(true);
			this.setMaximizable(true);
			
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 1116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 690, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the imagenOriginal
     */
    public Image getImagenOriginal() {
        return imagenOriginal;
    }

    /**
     * @param imagenOriginal the imagenOriginal to set
     */
    public void setImagenOriginal(Image imagenOriginal) {
        this.imagenOriginal = imagenOriginal;
    }
    
    public void modificarImagen(Image imagen){
     // mandar la imagen como icono al jlabel
       
     this.jLabelImagen.setIcon(new ImageIcon(imagen));
        
    }
	
	public void deshacer(){
		Image aux = this.imagenRespaldo;
		this.imagenRespaldo = this.imagenOriginal;
		this.imagenOriginal = aux;
		int x=0;
	}
	
	
}
