/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Roberto Cruz Leija
 */
public class ImageJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ImageJFrame
     */
    public ImageJFrame(Image imagen) {
        initComponents();
        // mandar la imagen como icono al jlabel
        this.jLabelImage.setIcon(new ImageIcon(imagen));
        this.imagen2 = imagen;
        // redimensionar las dimensiones del jframe
         setSize(imagen.getWidth(null),imagen.getHeight(null));
		 this.addComponentListener(new ComponentAdapter() {
			@Override
			public void componentResized(ComponentEvent e) {
				super.componentResized(e); //To change body of generated methods, choose Tools | Templates.
			}
			 
		 });
		 this.setResizable(true);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImage)
                .addGap(0, 151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImage)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImage;
    // End of variables declaration//GEN-END:variables
	
	public void deshacer(){
		Image im = (Image) this.jLabelImage.getIcon();
		Image aux = this.imagen2;
		this.imagen2= im;
		this.jLabelImage.setIcon(new ImageIcon(aux));
	}
	
	public void cambio(){
		Image im = (Image) this.jLabelImage.getIcon();
		Image aux = this.imagen2;
		this.imagen2= im;
		this.jLabelImage.setIcon(new ImageIcon(aux));
	}
	public Image imagen2;
}
