/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import analisisenfrecuencias.filtros.*;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author yohov
 */
	public class JInternalFrameAFFiltros extends javax.swing.JInternalFrame {

	/**
	 * Creates new form JInternalFrameAFFiltros
	 */
	public JInternalFrameAFFiltros(Dimension s,JDesktopPane escritorio) {
		initComponents();
		this.setVisible(true);
		this.JLBX.setVisible(false);
		this.jSX.setVisible(false);
		FBPA = new FiltroButterworthyPasaAltas(170, s,10);
		FBPB = new FiltroButterworthyPasaBajas(170, s,10);
		FEPA = new FiltroExponencialPA(170, s,10);
		FEPB = new FiltroExponencialPB(170, s,10);
		FIPA = new FiltroIdealPasaAltas(170, s);
		FIPB = new FiltroIdealPasaBajas(170, s);
		FIPM = new FiltroIdealPM(170, s,150);
		FTPA = new FiltroTrapezoidalPA(170,150, s);
		FTPB = new FiltroTrapezoidalPB(170,150, s);
		FG = new FiltroGaussiano(170,0.1, s);
		this.FiltroPersonalizado = FBPA.crearFiltro();
		this.escritorio = escritorio;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jCBFiltros = new javax.swing.JComboBox<>();
        jSK0 = new javax.swing.JSlider();
        jSX = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        JLBK0 = new javax.swing.JLabel();
        JLBX = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        Filtro = new javax.swing.JLabel();

        setClosable(true);
        setForeground(java.awt.Color.darkGray);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(492, 387));
        setMinimumSize(new java.awt.Dimension(492, 387));

        jLayeredPane1.setBackground(new java.awt.Color(102, 102, 102));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración del Filtro"));
        jLayeredPane1.setForeground(new java.awt.Color(102, 102, 102));
        jLayeredPane1.setToolTipText("");

        jLabel1.setText("Tipo de Filtro: ");

        jCBFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtros", "Ideal PA", "Ideal PB", "Ideal PM", "Butterworth PA", "Butterworth PB", "Exponencial PA", "Exponencial PB", "Trapezoidal PA", "Trapezoidal PB", "Gaussiano", "Personalizado" }));
        jCBFiltros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBFiltrosItemStateChanged(evt);
            }
        });

        jSK0.setMajorTickSpacing(1);
        jSK0.setMaximum(360);
        jSK0.setMinimum(1);
        jSK0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSK0StateChanged(evt);
            }
        });

        jSX.setMajorTickSpacing(1);
        jSX.setMaximum(350);
        jSX.setMinimum(1);
        jSX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSXStateChanged(evt);
            }
        });

        jButton1.setText("ACEPTAR");

        JLBK0.setText("Radio");

        JLBX.setText("jLabel2");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jCBFiltros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSK0, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSX, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(JLBK0, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(JLBX, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSK0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBX)
                            .addComponent(JLBK0))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(JLBK0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSK0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JLBX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));
        jLayeredPane2.setAlignmentX(257.0F);
        jLayeredPane2.setAlignmentY(257.0F);
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(512, 512));

        jLayeredPane2.setLayer(Filtro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Filtro)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(Filtro)
                .addGap(0, 489, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSK0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSK0StateChanged
        // TODO add your handling code here:
		switch(jCBFiltros.getSelectedIndex()){
			case 1:{
				this.JLBX.setVisible(false);
				this.jSX.setVisible(false);
				this.Filtro.setIcon(new ImageIcon(this.FIPA.modificarFiltro(this.jSK0.getValue())));
				break;
			}
			case 2:{
				this.JLBX.setVisible(false);
				this.jSX.setVisible(false);
				this.Filtro.setIcon(new ImageIcon(this.FIPB.modificarFiltro(this.jSK0.getValue())));
				break;
			}
			case 3:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("FIPM");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FIPM.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 4:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("N");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FBPA.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 5:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("N");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FBPB.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 6:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("N");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FEPA.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 7:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("N");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FEPB.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 8:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("K1");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FTPA.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 9:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("K1");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FTPB.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 10:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("S");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FG.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 11:{
				JInternalFrameFiltroPersonalizado fp = new JInternalFrameFiltroPersonalizado(FiltroPersonalizado); 
				this.escritorio.add(fp);
			}
		}
    }//GEN-LAST:event_jSK0StateChanged

    private void jSXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSXStateChanged
        // TODO add your handling code here:
		switch(jCBFiltros.getSelectedIndex()){
			case 1:{
				this.JLBX.setVisible(false);
				this.jSX.setVisible(false);
				this.Filtro.setIcon(new ImageIcon(this.FIPA.modificarFiltro(this.jSK0.getValue())));
				break;
			}
			case 2:{
				this.JLBX.setVisible(false);
				this.jSX.setVisible(false);
				this.Filtro.setIcon(new ImageIcon(this.FIPB.modificarFiltro(this.jSK0.getValue())));
				break;
			}
			case 3:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("FIPM");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FIPM.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 4:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("N");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FBPA.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 5:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("N");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FBPB.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 6:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("N");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FEPA.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 7:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("N");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FEPB.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 8:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("K1");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FTPA.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 9:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("K1");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FTPB.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
			case 10:{
				this.JLBX.setVisible(true);
				this.JLBX.setText("S");
				this.jSX.setVisible(true);
				this.Filtro.setIcon(new ImageIcon(this.FG.modificarFiltro(this.jSK0.getValue(),this.jSX.getValue())));
				break;
			}
		}
    }//GEN-LAST:event_jSXStateChanged

    private void jCBFiltrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBFiltrosItemStateChanged
        // TODO add your handling code here:
		if(jCBFiltros.getSelectedIndex() == 11){
			fp  = new JInternalFrameFiltroPersonalizado(FiltroPersonalizado); 
			this.Filtro.setIcon(new ImageIcon(this.FiltroPersonalizado));
			this.escritorio.add(fp);
			actualizarImg();
		}

    }//GEN-LAST:event_jCBFiltrosItemStateChanged
	
	public void actualizarImg(){
		Runnable r = new Runnable() {
			@Override
			public void run() {
				while(jCBFiltros.getSelectedIndex() == 11){
					Filtro.setIcon(new ImageIcon(fp.getFiltroImg()));
				}
			}
		};
		Thread t = new Thread(r);
		t.start();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Filtro;
    private javax.swing.JLabel JLBK0;
    private javax.swing.JLabel JLBX;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JSlider jSK0;
    private javax.swing.JSlider jSX;
    // End of variables declaration//GEN-END:variables
	private FiltroButterworthyPasaAltas FBPA;
	private FiltroButterworthyPasaBajas FBPB;
	private FiltroExponencialPA FEPA;
	private FiltroExponencialPB FEPB;
	private FiltroIdealPasaAltas FIPA;
	private FiltroIdealPasaBajas FIPB;
	private FiltroIdealPM FIPM;
	private FiltroTrapezoidalPA FTPA;
	private FiltroTrapezoidalPB FTPB;
	private FiltroGaussiano FG;
	private JDesktopPane escritorio;
	private JInternalFrameFiltroPersonalizado fp;
	private Image FiltroPersonalizado;
}
