/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import filtrosespaciales.FiltroEspacial;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.DefaultMetalTheme;
import javax.swing.plaf.metal.MetalLookAndFeel;
import lectura.ImageManager;

/**
 *
 * @author yohov
 */
public class Main extends javax.swing.JFrame {

	/**
	 * Creates new form Main
	 */
	public Main() {
		initComponents();
		MetalLookAndFeel.setCurrentTheme(new DefaultMetalTheme());
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbepane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        tabbepane.setBackground(new java.awt.Color(0, 0, 0));
        tabbepane.setForeground(new java.awt.Color(102, 102, 102));
        tabbepane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabbepane.setDoubleBuffered(true);
        tabbepane.setMinimumSize(new java.awt.Dimension(1280, 720));

        jMenu1.setText("File");

        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAbrir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Filtros Espaciales");

        jMenuItem1.setText("Escala de Grises");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Convolución");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem5.setText("Dispersion Histograma");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Expansión Histograma");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem8.setText("Umbralización / Iluminación");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem7.setText("Ruido");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setText("Temperatura");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Imagen");

        jMenuItem3.setText("Deshacer");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Histograma");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Análisis de Frecuencias");

        jMenuItem10.setText("Filtros");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        // TODO add your handling code here:	
		
		Image io = ImageManager.openImage();
		ImagenJInternalFrame aux = new ImagenJInternalFrame(io);
		
//		this.jDesktopPane1.add(panel1);

	//	tabbepane.add(this.escritorio);
		JDesktopPane escritorio =new JDesktopPane();
		escritorio.setBackground(Color.red);
		escritorio.add(aux);
		this.escritorios.add(escritorio);
		
		tabbepane.addTab("Imagen "+tabbepane.getTabCount(),null, this.escritorios.get(this.escritorios.size()-1),"Imagen "+tabbepane.getTabCount());
		
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
//		int index = this.tabbepane.getSelectedIndex();
//		JInternalFrame fi = this.escritorios.get(index).getSelectedFrame();
//        GrisJInternalFrame frame = new GrisJInternalFrame(fi);
//		System.out.println("Index: "+this.tabbepane.getSelectedIndex());
//		this.escritorios.get(index).add(frame);
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		aux2.modificarImagen(FiltroEspacial.generaEscalaGrises(aux2.getImagenOriginal()));

   //     this.escritorio.add(frame);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		Convolucion c = new Convolucion(aux2.getImagenOriginal(),aux);
		this.escritorios.get(index).add(c);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
//		aux2.modificarImagen(FiltroEspacial.generaEscalaGrises(aux2.getImagenOriginal()));
		aux2.deshacer();
		aux2.modificarImagen(aux2.getImagenOriginal());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

		int index = this.tabbepane.getSelectedIndex();
		
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		lectura.Grafica g = new lectura.Grafica("Tonos","Frecuencia","Histograma de Frecuencias de: "+this.tabbepane.getTitleAt(index));
		
		
		g.agregarSerie("Rojo", aux2.getHistograma()[0]);
		g.agregarSerie("Azul", aux2.getHistograma()[2]);
		g.agregarSerie("Verde", aux2.getHistograma()[1]);
		g.crearYmostrarGrafica();
		
//		Histograma h = new Histograma(aux2.getHistograma());
//		this.escritorios.get(index).add(h);
		
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		aux2.modificarImagen(filtrosespaciales.DispersionHistograma.ecualizarHistograma(aux2.getHistograma(), aux2.getImagenOriginal()));
		
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here: Expansion Histograma
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		
		lectura.Grafica g = new lectura.Grafica("Tonos","Frecuencia","Histograma de Frecuencias de: "+this.tabbepane.getTitleAt(index));
		
		
		g.agregarSerie("Rojo", aux2.getHistograma()[0]);
		g.agregarSerie("Azul", aux2.getHistograma()[2]);
		g.agregarSerie("Verde", aux2.getHistograma()[1]);
		g.crearYmostrarGrafica();
		
		JInternalFrameExpansionHistograma expH = new JInternalFrameExpansionHistograma(aux2.getImagenOriginal(),aux2);
		this.escritorios.get(index).add(expH);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		UmbralizacionSimple c = new UmbralizacionSimple(aux2.getImagenOriginal(),aux);
		this.escritorios.get(index).add(c);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here://///////////////
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		JInternalFrameRuido c = new JInternalFrameRuido(aux2.getImagenOriginal(),aux);
		this.escritorios.get(index).add(c);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		JInternalFrameTemperatura c = new JInternalFrameTemperatura(aux2.getImagenOriginal(),aux);
		this.escritorios.get(index).add(c);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
		int index = this.tabbepane.getSelectedIndex();
		JInternalFrame aux = this.escritorios.get(index).getSelectedFrame();
		ImagenJInternalFrame aux2 = (ImagenJInternalFrame) aux;
		JInternalFrameAFFiltros c = new JInternalFrameAFFiltros(new Dimension(470,470),this.escritorios.get(index));
		this.escritorios.get(index).add(c);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JTabbedPane tabbepane;
    // End of variables declaration//GEN-END:variables
	ArrayList<JDesktopPane> escritorios =  new ArrayList();
}
